# Generated by Django 4.1.2 on 2022-11-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=200)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.contacto')),
            ],
        ),
    ]
